version: "3.9"

services:
  nginx:
    image: yuta2025/shizen-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - rails
    volumes:
      - certbot_www:/var/www/certbot:rw
      - certbot_conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: >
      certonly --webroot
      -w /var/www/certbot
      -d zasso-lens.com
      -d www.zasso-lens.com
      --email ${LETSENCRYPT_EMAIL}
      --agree-tos
      --no-eff-email
    depends_on:
      - nginx
    profiles: ["cert"]

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot renew --webroot -w /var/www/certbot"
    depends_on:
      - nginx
    profiles: ["cert"]

  frontend:
    image: yuta2025/shizen-frontend:latest
    container_name: frontend
    environment:
      NODE_ENV: production
    depends_on:
      - rails

  rails:
    image: yuta2025/shizen-rails:latest
    container_name: rails
    environment:
      RAILS_ENV: production

      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}

      DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      FRONTEND_URL: ${FRONTEND_URL}
    command: bash -c "./bin/rails db:create db:migrate && ./bin/rails s -b 0.0.0.0 -p 3000"
    ports:
      - "5000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
  certbot_www:
  certbot_conf:
