version: "3.9"

services:
  nginx:
    image: yuta2025/shizen-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - rails

  frontend:
    image: yuta2025/shizen-frontend:latest
    container_name: frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://zasso-lens.com
      NEXT_PUBLIC_FRONT_BASE_URL: http://zasso-lens.com
    depends_on:
      - rails

  rails:
    image: yuta2025/shizen-rails:latest
    container_name: rails
    command: bash -c "./bin/rails db:create db:migrate && ./bin/rails s -b 0.0.0.0 -p 3000"
    ports:
      - "5000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./rails/.env

  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_production
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
