version: "3.9"

services:
  nginx:
    image: yuta2025/shizen-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - rails

  frontend:
    image: yuta2025/shizen-frontend:latest
    container_name: frontend
    environment:
      - NODE_ENV: production
      - NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - rails

  rails:
    image: yuta2025/shizen-rails:latest
    container_name: rails
    command: bash -c "./bin/rails db:create db:migrate && ./bin/rails s -b 0.0.0.0 -p 3000"
    ports:
      - "5000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SAKURA_ACCESS_KEY: ${SAKURA_ACCESS_KEY}
      SAKURA_SECRET_KEY: ${SAKURA_SECRET_KEY}
      SAKURA_BUCKET: ${SAKURA_BUCKET}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_production
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
