name: Build Frontend Image

on:
  push:
    branches:
      - main
      - create-production

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yuta2025
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push frontend image
        run: |
          docker build --no-cache -f frontend/Dockerfile.prod \
            --build-arg NEXT_PUBLIC_BACKEND_URL=http://163.43.209.197:5000 \
            --build-arg NEXT_PUBLIC_FRONT_BASE_URL=http://zasso-lens.com \
            -t yuta2025/shizen-frontend:latest \
            ./frontend
          docker push yuta2025/shizen-frontend:latest
