name: Build Nginx Image

on:
  push:
    branches:
      - main
      - feature/recreate_production_deploy
    paths:
      - "nginx/**"
      - "docker-compose.prod.yml"

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yuta2025
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push nginx image
        run: |
          docker build -f nginx/Dockerfile \
            -t yuta2025/shizen-nginx:latest \
            ./nginx
          docker push yuta2025/shizen-nginx:latest
