name: Build Rails Image

on:
  push:
    branches:
      - main
    paths:
      - "rails/**"
      - "docker-compose.prd.yml"

jobs:
  build_rails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yuta2025
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push rails image
        run: |
          docker build -f rails/Dockerfile.prod \
            -t yuta2025/shizen-rails:latest \
            ./rails
          docker push yuta2025/shizen-rails:latest
